name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the feature you'd like to see.
      placeholder: "What's the feature about..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem would this feature solve? What's your use case?
      placeholder: "This would solve... because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "I think it should work like this..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "I also considered..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical/blocking my work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change)
        - Medium (moderate effort)
        - Complex (significant work)
        - Very Complex (major feature)
        - I don't know

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples.
      placeholder: "Additional context..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature would benefit other users too
          required: true
        - label: I understand this is a suggestion and may not be implemented
          required: true
